version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgresadmin
      POSTGRES_DB: cloakblog
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # 로컬 디렉토리와 컨테이너의 데이터 디렉토리 연결
    ports:
      - "5432:5432"  # 로컬 포트 5432와 컨테이너 포트 매핑
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
